# -*- coding: utf-8 -*-
"""Thesis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IREynCRx0SHkBlLtCSxo-8Ec5Cy6SAdt
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install SimpleITK

cd /content/drive/My Drive/Neural Network Dataset/testing/patient0001

from glob import glob
import numpy as np
import os
import skimage.io as io
from PIL import Image
from prefetch_generator import background
from keras.preprocessing.image import ImageDataGenerator
import random

def read_mhd(img_path):
        img = io.imread(img_path, plugin='simpleitk').squeeze()
        img = np.array(Image.fromarray(img).resize([256, 256]))
        img = np.expand_dims(img, axis=2)
        print(img)

read_mhd('patient0001_4CH_ED.mhd')